# yaml-language-server: $schema=https://github.com/eclipse-symphony/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json

name: VirtualMachine
version: 1.0.0
summary: Deploys an Azure VM using Azure Compute Gallery image
description: Deploys an Azure VM using an existing VNet and subnet.

runner: ARM
templatePath: env.ARM.template.json

parameters:

# REQUIRED - must be full Compute Gallery image resource ID
#- id: "imageReference"
 # name: "Image Reference (Compute Gallery Resource ID)"
  #type: "string"
  #required: true

- id: "imagePublisher"
  name: "Image publisher"
  type: "string"
  required: true

- id: "imageOffer"
  name: "Image offer"
  type: "string"
  required: true

- id: "imageSku"
  name: "Image Sku"
  type: "string"
  required: true

# REQUIRED
- id: "location"
  name: "Location"
  type: "string"
  required: true

#  EXISTING VNET FLAG (default true for your case)
- id: "useExistingVNet"
  name: "Use Existing VNet"
  type: "string"
  required: false
  default: "true"

#  EXISTING VNET DETAILS
- id: "virtualNetworkName"
  name: "Virtual Network Name"
  type: "string"
  required: true

- id: "virtualNetworkResourceGroupName"
  name: "Virtual Network Resource Group"
  type: "string"
  required: true

#  NETWORK (NIC + SUBNET)
- id: "networkInterfaceName"
  name: "Network Interface Name"
  type: "string"
  required: true

- id: "networkInterfaceIPConfigurationName"
  name: "NIC IP Configuration Name"
  type: "string"
  required: true

- id: "networkInterfaceIPConfigurationSubnetName"
  name: "Subnet Name"
  type: "string"
  required: true

#  VM
- id: "virtualMachineName"
  name: "Virtual Machine Name"
  type: "string"
  required: true

#  OPTIONAL (with safe defaults from ARM)
- id: "virtualMachineSize"
  name: "VM Size"
  type: "string"
  required: false
  default: "Standard_D2ps_v5"

- id: "osDiskType"
  name: "OS Disk Type"
  type: "string"
  required: false
  default: "StandardSSD_LRS"

- id: "osDiskDeleteOption"
  name: "OS Disk Delete Option"
  type: "string"
  required: false
  default: "Delete"

- id: "virtualMachineZone"
  name: "Availability Zone"
  type: "string"
  required: false
  default: "1"

- id: "nicDeleteOption"
  name: "NIC Delete Option"
  type: "string"
  required: false
  default: "Delete"
